[build.env]
passthrough = [
  "RUST_BACKTRACE",
  "RUST_LOG",
]

# Fix already here https://github.com/cross-rs/cross/blob/main/docker/netbsd.sh
# But no new release so temporary fix here instead
# Remove once next cross release is out
[target.x86_64-unknown-netbsd]
image = "ghcr.io/cross-rs/x86_64-unknown-netbsd:main"
